# Generated by Django 5.2.3 on 2025-07-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_perfil_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tiktok_user',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='titulo',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='perfil',
            name='x_user',
            field=models.CharField(blank=True, max_length=50, verbose_name='Usuário do X'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
