# Generated by Django 5.2.3 on 2025-07-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfil_bio_perfil_facebook_url_perfil_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
    ]
