# Generated by Django 5.2.3 on 2025-07-15 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_pontuacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pontuacao',
        ),
    ]
