# Generated by Django 5.2.3 on 2025-07-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_delete_pontuacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultima_insignia',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
