# Generated by Django 5.2.3 on 2025-07-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_usuario_ultima_insignia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ultima_insignia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
